// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aDRj31GiXKzzbdsQpZSOUAMRfzVBsuE',
    appId: '1:250225425929:web:409f164755666ad83a02d8',
    messagingSenderId: '250225425929',
    projectId: 'nandikrushi-35ddb',
    authDomain: 'nandikrushi-35ddb.firebaseapp.com',
    storageBucket: 'nandikrushi-35ddb.appspot.com',
    measurementId: 'G-PS9C9500MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5eidVV2rDAml4j-h0h8yZYu1yZJXxcf8',
    appId: '1:250225425929:android:02d5f89ddb411d5f3a02d8',
    messagingSenderId: '250225425929',
    projectId: 'nandikrushi-35ddb',
    storageBucket: 'nandikrushi-35ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmvpgvCI61KzrTwaQgzKsMKqAHLfv0Lzc',
    appId: '1:250225425929:ios:68703909ca68fd933a02d8',
    messagingSenderId: '250225425929',
    projectId: 'nandikrushi-35ddb',
    storageBucket: 'nandikrushi-35ddb.appspot.com',
    androidClientId: '250225425929-9vrr2p1m92k6cuoukbcohq9npikcq75l.apps.googleusercontent.com',
    iosClientId: '250225425929-i7ca6d5dckfp5rq45cejs87rm5p2g4gs.apps.googleusercontent.com',
    iosBundleId: 'com.nandikrushi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmvpgvCI61KzrTwaQgzKsMKqAHLfv0Lzc',
    appId: '1:250225425929:ios:68703909ca68fd933a02d8',
    messagingSenderId: '250225425929',
    projectId: 'nandikrushi-35ddb',
    storageBucket: 'nandikrushi-35ddb.appspot.com',
    androidClientId: '250225425929-9vrr2p1m92k6cuoukbcohq9npikcq75l.apps.googleusercontent.com',
    iosClientId: '250225425929-i7ca6d5dckfp5rq45cejs87rm5p2g4gs.apps.googleusercontent.com',
    iosBundleId: 'com.nandikrushi',
  );
}
